-- CreateEnum
CREATE TYPE "EventCategory" AS ENUM ('WEDDING', 'ENGAGEMENT', 'BIRTHDAY', 'GRADUATION', 'CORPORATE_GATHERING', 'REUNION', 'FESTIVAL_CONCERT', 'GRAND_OPENING', 'BABY_SHOWER', 'COMMUNITY_EVENT', 'OTHER');

-- AlterTable
ALTER TABLE "events" ADD COLUMN "category" "EventCategory" NOT NULL DEFAULT 'OTHER';
